### ISSUE TITLE
Report contains no files

### ISSUE THREAD

**Issue by zambrovski** [codecov/example-kotlin#4]
Hi,

I'm trying to use CodeCov for Kotlin built with Maven driven by Travis CI.
Your example doesn't seem to work with this setup. Kotlin Version is 1.2.10

I'm using the recent JaCoCo plugin:

      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.7.9</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

and get a generated report in `target/site/jacoco/jacoco.xml`. The Travis CI build reports:

```
0.76s$ bash <(curl -s https://codecov.io/bash)
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-e3f8e98

==> Travis CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Appending build variables
    + TRAVIS_OS_NAME
    + TRAVIS_JDK_VERSION
==> Reading reports
    + ./target/site/jacoco/jacoco.xml bytes=21760
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=1cfb7ea767694b90fe9ce71658f1afa47fed702b&build=31.1&build_url=&name=&tag=&slug=toolisticon%2Fspringboot-swagger-starter&service=travis&flags=&pr=false&job=319186260
    -> Pinging Codecov
    -> Uploading
    -> View reports at https://codecov.io/github/toolisticon/springboot-swagger-starter/commit/1cfb7ea767694b90fe9ce71658f1afa47fed702b

Done. Your build exited with 0.
```

If I visit the CodeCov report page, it says that the report doesn't contain any files. (No files found in report.)

Any Ideas?

Kind regards,

Simon

**Comment by stevepeak** [comment]
Hey @zambrovski 

> The raw uploaded report is [here](https://s3-us-west-2.amazonaws.com/codecov/v4/raw/2017-12-20/391053F9E0D16F032EB663CF1A9F0D2D/1cfb7ea767694b90fe9ce71658f1afa47fed702b/b44bef38-ac22-492d-8aca-a67e85ec06d4.txt)

The issue is mapping file back to the correct source. The report shows files at 

```
io/toolisticon/springboot/swagger/SpringBootSwaggerAutoConfiguration.kt 
io/toolisticon/springboot/swagger/Properties.kt
```
But your repository has them at 

```
src/main/kotlin/SpringBootSwaggerAutoConfiguration.kt
```

**Comment by zambrovski** [comment]
👍
